version: '3.8'

services:
  calendario-festivos-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      BASE_URL: 'http://localhost:3000/api'
      NODE_ENV: prod