# fly.toml app configuration file generated for spain-holidays-calendar on 2024-04-20T14:19:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spain-holidays-calendar'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[env]
  BASE_URL = "https://www.calendariovacaciones.com"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
