export const provinceInfo: Record<string, string> = {
  'madrid': 'En la Comunidad de Madrid, los festivos están marcados por una rica mezcla de tradición y cultura. Destaca el 2 de mayo, Día de la Comunidad de Madrid, que conmemora el levantamiento de 1808 y se celebra con eventos institucionales y festejos en las calles. Asimismo, el 15 de mayo se celebra San Isidro Labrador, el patrón de la capital, donde los madrileños se visten de chulapos, bailan chotis y acuden a la pradera para disfrutar de rosquillas y limonada. Durante el otoño, el 9 de noviembre se rinde homenaje a la Virgen de la Almudena. Estos días libres, junto con los puentes nacionales, son aprovechados por los residentes para realizar escapadas a la sierra, disfrutar de la extensa oferta cultural y gastronómica de la ciudad o descansar en familia.',
  'barcelona': 'El calendario laboral de Barcelona incluye festividades de gran arraigo popular y cultural. El 11 de septiembre, la Diada Nacional de Catalunya, es un día clave lleno de actos institucionales y manifestaciones ciudadanas. El 23 de abril, aunque tradicionalmente laborable o festivo según el año, Sant Jordi llena las calles de libros y rosas, siendo uno de los días más especiales. La gran fiesta local es La Mercè, el 24 de septiembre, con impresionantes correfocs, castellers y conciertos por toda la ciudad. Los barceloneses aprovechan estos puentes y festivos para disfrutar de la costa mediterránea, hacer rutas por el Pirineo catalán o sumergirse en la vibrante vida de los barrios de la ciudad.',
  'valencia': 'En Valencia, los festivos se viven con gran intensidad, destacando, sin duda, la festividad de San José el 19 de marzo, que culmina las famosas Fallas. Durante estos días, la ciudad se transforma con el olor a pólvora, los monumentos artísticos, las mascletàs y la ofrenda floral, atrayendo a miles de visitantes. El 9 de octubre se celebra el Día de la Comunidad Valenciana (Nou d\'Octubre), conmemorando la entrada de Jaume I, donde es tradición regalar la "Mocaorà", unos dulces de mazapán. Estos periodos de descanso permiten a los valencianos disfrutar de su excelente gastronomía local, escapar a sus magníficas playas o visitar el interior de la región.',
  'sevilla': 'Sevilla vive sus festivos con profunda devoción y alegría. Aunque no siempre son festivos oficiales laborales, la Semana Santa y la Feria de Abril marcan el pulso de la ciudad. El miércoles de Feria y el Corpus Christi son festivos locales que se celebran con gran entusiasmo. El 28 de febrero, Día de Andalucía, es un festivo autonómico de gran importancia, celebrado con banderas blancas y verdes, cantos del himno y el tradicional desayuno de pan con aceite y azúcar. Los sevillanos utilizan estos días festivos y puentes para disfrutar del buen clima, visitar los pueblos de la provincia o reunirse con familiares y amigos en reuniones festivas.',
  'bizkaia': 'El calendario festivo en Bizkaia refleja sus fuertes raíces culturales y tradiciones vascas. En Bilbao, la Semana Grande o Aste Nagusia (generalmente en agosto) marca las principales festividades locales, con la icónica Marijaia, conciertos y fuegos artificiales. El 25 de julio, Santiago Apóstol, o el 31 de julio, San Ignacio de Loyola (patrón de Bizkaia y Gipuzkoa), suelen ser fechas señaladas en el calendario laboral. Los bizkainos disfrutan de sus puentes realizando excursiones al monte (como la subida al Gorbea), visitando la escarpada costa vasca, disfrutando de su mundialmente conocida gastronomía de pintxos o participando en las numerosas romerías y fiestas populares de los diferentes municipios.'
};

export function getProvinceDescription(province: string): string | null {
  const normalized = province.toLowerCase().trim().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  return provinceInfo[normalized] || null;
}
