name: Build Android APK and Angular App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build

    - name: Set up Android
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17.x'

    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleRelease
        ./gradlew bundleRelease

    - name: Move files
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/app-release.apk
        mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/app-release.aab
    
    - name: Sign Apk File
      id: sign_app
      uses: ilharp/sign-android-release@v1.0.4
      with:
        releaseDir: app/build/outputs
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Package dist folder
      run: zip -r dist.zip dist

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          app/build/outputs/app-release.apk
          app/build/outputs/app-release.aab
          dist.zip

