name: Build Android APK and Angular App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build

    - name: Set up Android
      uses: actions/setup-java@v1
      with:
        java-version: '17.x'

    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleRelease

    - name: Package dist folder
      run: zip -r dist.zip dist

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifacts
        path: |
          dist/
          android/app/build/outputs/apk/debug/*.apk

    - name: Create release draft with APK
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        files: |
          android/app/build/outputs/apk/release/app-release.apk
          dist.zip
