name: Deploy Docker to Fly.io

on:
  release:
    types: [published]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  APP_NAME: spain-holidays-calendar
  FLY_API_TOKEN:  ${{ secrets.FLY_API_TOKEN }}
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Download artifact
      run: |
        curl -sL -o dist.zip "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/dist.zip"

    - name: Unzip dist.zip
      run: unzip dist.zip -d ./

    - name: Install cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: 'v2.1.1'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract image full name lowercase
      id: image_fullname
      run: |
        full_name=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
        echo "Lowercase fullname: $full_name"
        echo "::set-output name=lowercase_name::$full_name"

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.image_fullname.outputs.lowercase_name }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.image_fullname.outputs.lowercase_name }}:latest,${{ steps.image_fullname.outputs.lowercase_name }}:${{ github.event.release.tag_name }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    #- name: Setup flyctl
    #  uses: superfly/flyctl-actions/setup-flyctl@master

    #- name: Deploy to Fly.io
    #  run: |
    #    flyctl deploy -i ${{ steps.image_fullname.outputs.lowercase_name }}:${{ github.event.release.tag_name }} --app spain-holidays-calendar
    